### ISSUE TITLE
Help Regarding GSoC

### ISSUE THREAD

**Issue by yumsuncoder** [surajkumar-sk/morseconvertor#1]
@surajkumar-sk I am yum sun I beginner in GSoC and open source I wanted to ask a question can you please share your email yamhello10@gmail.com . After seeing your contributions I think you are really good contributor. I just wanted to ask only few questions. Please Suraj Kumar

**Comment by surajkumar-sk** [comment]
@yumsuncoder this repo is like sahara desert. You wont be seeing anyone around, so feel free to ask anything over here. Email wont be necessary .

**Comment by yumsuncoder** [comment]
@surajkumar-sk I am beginner in open source I saw you made huge number of contributions and I thought of applying for GSoC in shaka-player but then I thought if I apply in the same project as you I won't have chance because you are familiar with code and made amazing contributions. So, I just wanted to ask in which project you are going to apply so I don't waste my proposal on that project and contribute in new org.? Your answer would help me saving my proposal, so I can contribute in another org. Thanking you in advance.

**Comment by yumsuncoder** [comment]
@surajkumar-sk please reply it will save my time and efforts

**Comment by surajkumar-sk** [comment]
@yumsuncoder you are funny. :-) , I haven't decided yet. The project ideas are quite interesting, I want to work on all of them. but it's not possible. so I am yet to decide on my proposal. I might apply for the UI side of shaka player. You want to apply to a project which has the least competition, then you got the whole thing of programming wrong. Its not about getting selected or not in some competition, you have a whole life ahead, so have fun with every minute and every line of code. Apply for a project which you feel might challenge or improve your ability. it doesn't matter if you get selected or not. if you get selected 'hooray' but if you dont move on, GSOC will return again and there are many other competitions too. so just choose something. doing which you will have fun.
I hope you have a great day and a great proposal

**Comment by surajkumar-sk** [comment]
@yumsuncoder just for my satisfaction can I get your real account name. I want to know whom I a talking to. it's on you, if you don't want to reveal yourself it's ok.

**Comment by yumsuncoder** [comment]
@surajkumar-sk this isn't my fake account this is my real account. Sorry, for the late reply I was affected with covid-19.

**Comment by yumsuncoder** [comment]
@surajkumar-sk BTW can I know in which project you applied?? I just meant as friend because today is the last day to apply.
